# Generated by Django 5.2.8 on 2025-11-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('computadora', 'Computadora'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('proyector', 'Proyector'), ('impresora', 'Impresora'), ('router', 'Router'), ('switch', 'Switch'), ('servidor', 'Servidor'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('baja', 'De Baja')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_red', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('lan', 'LAN'), ('wlan', 'WLAN'), ('wan', 'WAN')], max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En Mantenimiento')], max_length=20)),
                ('configuracion', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('reportada', 'Reportada'), ('en_reparacion', 'En Reparación'), ('resuelta', 'Resuelta')], default='reportada', max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
            ],
        ),
    ]
