# Generated by Django 5.2.8 on 2025-11-25 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField()),
                ('nombre', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nota_examen', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Examen')),
                ('nota_proyecto', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Proyecto Interdisciplinar')),
                ('nota_formativa', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4)),
                ('nota_sumativa', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4)),
                ('nota_final', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.asignatura')),
                ('año_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.aniolectivo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.estudiante')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.trimestre')),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura', 'trimestre', 'año_lectivo')},
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('trabajo_grupal', 'Trabajo Grupal'), ('tarea_individual', 'Tarea Individual'), ('proyecto_aula', 'Proyecto de Aula'), ('exposicion', 'Exposición'), ('investigacion', 'Investigación'), ('practica_laboratorio', 'Práctica de Laboratorio'), ('ejercicios_clase', 'Ejercicios en Clase'), ('portafolio', 'Portafolio Estudiantil'), ('personalizada', 'Personalizada')], default='personalizada', max_length=50)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='calificaciones.calificacion')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.paralelo'),
        ),
    ]
