# Generated by Django 5.2.8 on 2025-11-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('evaluador', models.CharField(max_length=100)),
                ('puntuacion_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('categoria', models.CharField(choices=[('barreras_fisicas', 'Barreras Físicas'), ('senalizacion', 'Señalización'), ('espacios_aprendizaje', 'Espacios de Aprendizaje'), ('recursos_tecnologicos', 'Recursos Tecnológicos'), ('politicas_practicas', 'Políticas y Prácticas')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta Prioridad'), ('media', 'Media Prioridad'), ('baja', 'Baja Prioridad')], max_length=20)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclusion.encuestainclusion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Excelente')])),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclusion.encuestainclusion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclusion.preguntainclusion')),
            ],
            options={
                'unique_together': {('encuesta', 'pregunta')},
            },
        ),
    ]
